In [1]:
import pandas as pd 
import plotly.express as px

In [2]:
df=pd.read_csv("employee_attrition_dataset_10000.csv")
df

,Employee_ID,Age,Gender,Marital_Status,Department,Job_Role,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,...,Overtime,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked,Attrition
0,1,58,Male,Single,Finance,Manager,5,7332,81,24,...,No,9,48,16,4,1,1,49,3,No
1,2,48,Female,Divorced,HR,Assistant,4,6069,55,18,...,Yes,9,57,10,4,1,1,25,1,No
2,3,34,Female,Married,Marketing,Manager,4,11485,65,6,...,Yes,3,55,1,1,4,3,21,1,Yes
3,4,27,Female,Divorced,HR,Manager,4,18707,28,12,...,No,9,53,2,3,4,1,46,2,No
4,5,40,Male,Married,HR,Analyst,1,16398,92,3,...,No,1,54,11,1,1,1,43,4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,22,Female,Divorced,Marketing,Manager,5,4276,27,17,...,Yes,3,36,3,4,2,3,18,2,No
9996,9997,35,Female,Divorced,Marketing,Executive,3,10327,60,19,...,No,5,59,4,4,3,4,31,1,No
9997,9998,23,Male,Divorced,IT,Manager,3,12592,68,10,...,Yes,4,54,10,4,4,2,12,1,Yes
9998,9999,42,Female,Single,Marketing,Manager,3,9287,26,18,...,Yes,9,51,16,3,2,2,18,3,No
9999,10000,39,Female,Divorced,Finance,Executive,2,7225,54,16,...,Yes,4,51,6,4,1,1,6,2,Yes

### data understanding

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Employee_ID                    10000 non-null  int64
 1   Age                            10000 non-null  int64
 2   Gender                         10000 non-null  object
 3   Marital_Status                 10000 non-null  object
 4   Department                     10000 non-null  object
 5   Job_Role                       10000 non-null  object
 6   Job_Level                      10000 non-null  int64
 7   Monthly_Income                 10000 non-null  int64
 8   Hourly_Rate                    10000 non-null  int64
 9   Years_at_Company               10000 non-null  int64
 10  Years_in_Current_Role          10000 non-null  int64
 11  Years_Since_Last_Promotion     10000 non-null  int64
 12  Work_Life_Balance              10000 non-null  int64
 13  Job_Satisfaction               10000 non-null  int64
 14  Performance_Rating             10000 non-null  int64
 15  Training_Hours_Last_Year       10000 non-null  int64
 16  Overtime                       10000 non-null  object
 17  Project_Count                  10000 non-null  int64
 18  Average_Hours_Worked_Per_Week  10000 non-null  int64
 19  Absenteeism                    10000 non-null  int64
 20  Work_Environment_Satisfaction  10000 non-null  int64
 21  Relationship_with_Manager      10000 non-null  int64
 22  Job_Involvement                10000 non-null  int64
 23  Distance_From_Home             10000 non-null  int64
 24  Number_of_Companies_Worked     10000 non-null  int64
 25  Attrition                      10000 non-null  object
dtypes: int64(20), object(6)
memory usage: 2.0+ MB

In [4]:
df.describe().round(2)

,Employee_ID,Age,Job_Level,Monthly_Income,Hourly_Rate,Years_at_Company,Years_in_Current_Role,Years_Since_Last_Promotion,Work_Life_Balance,Job_Satisfaction,Performance_Rating,Training_Hours_Last_Year,Project_Count,Average_Hours_Worked_Per_Week,Absenteeism,Work_Environment_Satisfaction,Relationship_with_Manager,Job_Involvement,Distance_From_Home,Number_of_Companies_Worked
count,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00,10000.00
mean,5000.50,39.56,2.99,11436.72,57.03,14.94,7.45,4.47,2.50,3.04,2.51,49.59,4.98,44.47,9.41,2.49,2.49,2.51,25.27,2.52
std,2886.90,11.45,1.41,4926.53,24.70,8.43,4.04,2.89,1.11,1.41,1.12,28.80,2.58,8.61,5.76,1.12,1.12,1.12,14.22,1.11
min,1.00,20.00,1.00,3000.00,15.00,1.00,1.00,0.00,1.00,1.00,1.00,0.00,1.00,30.00,0.00,1.00,1.00,1.00,1.00,1.00
25%,2500.75,30.00,2.00,7182.50,36.00,8.00,4.00,2.00,2.00,2.00,2.00,25.00,3.00,37.00,4.00,1.00,1.00,2.00,13.00,2.00
50%,5000.50,40.00,3.00,11401.50,57.00,15.00,7.00,4.00,2.00,3.00,3.00,49.00,5.00,45.00,9.00,2.00,2.00,3.00,25.00,2.00
75%,7500.25,49.00,4.00,15679.50,78.00,22.00,11.00,7.00,3.00,4.00,4.00,75.00,7.00,52.00,14.00,4.00,3.00,3.00,37.00,4.00
max,10000.00,59.00,5.00,19999.00,99.00,29.00,14.00,9.00,4.00,5.00,4.00,99.00,9.00,59.00,19.00,4.00,4.00,4.00,49.00,4.00

In [5]:
df.select_dtypes(include='object').describe()

        Gender Marital_Status Department Job_Role Overtime Attrition
count    10000          10000      10000    10000    10000     10000
unique       2              3          5        4        2         2
top     Female        Married  Marketing  Analyst       No        No
freq      5042           3375       2133     2572     5103      8003

### clean data

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.isnull().sum()

Employee_ID                      0
Age                              0
Gender                           0
Marital_Status                   0
Department                       0
Job_Role                         0
Job_Level                        0
Monthly_Income                   0
Hourly_Rate                      0
Years_at_Company                 0
Years_in_Current_Role            0
Years_Since_Last_Promotion       0
Work_Life_Balance                0
Job_Satisfaction                 0
Performance_Rating               0
Training_Hours_Last_Year         0
Overtime                         0
Project_Count                    0
Average_Hours_Worked_Per_Week    0
Absenteeism                      0
Work_Environment_Satisfaction    0
Relationship_with_Manager        0
Job_Involvement                  0
Distance_From_Home               0
Number_of_Companies_Worked       0
Attrition                        0
dtype: int64

### Check Feature Imbalance and Unique Values

In [8]:
for col in df.select_dtypes(include='object').columns:
    print(df[col].value_counts())
    print('-' * 50)

Gender
Female    5042
Male      4958
Name: count, dtype: int64
--------------------------------------------------
Marital_Status
Married     3375
Divorced    3330
Single      3295
Name: count, dtype: int64
--------------------------------------------------
Department
Marketing    2133
Sales        2008
Finance      1990
HR           1953
IT           1916
Name: count, dtype: int64
--------------------------------------------------
Job_Role
Analyst      2572
Assistant    2538
Executive    2476
Manager      2414
Name: count, dtype: int64
--------------------------------------------------
Overtime
No     5103
Yes    4897
Name: count, dtype: int64
--------------------------------------------------
Attrition
No     8003
Yes    1997
Name: count, dtype: int64
--------------------------------------------------

In [9]:
from datasist.structdata import detect_outliers 
for col in df.select_dtypes(include = 'number').columns :
    outliers = detect_outliers(data = df , n = 0 , features = [col])
    print(col)
    print(outliers)
    print('-'*50)

Employee_ID
[]
--------------------------------------------------
Age
[]
--------------------------------------------------
Job_Level
[]
--------------------------------------------------
Monthly_Income
[]
--------------------------------------------------
Hourly_Rate
[]
--------------------------------------------------
Years_at_Company
[]
--------------------------------------------------
Years_in_Current_Role
[]
--------------------------------------------------
Years_Since_Last_Promotion
[]
--------------------------------------------------
Work_Life_Balance
[]
--------------------------------------------------
Job_Satisfaction
[]
--------------------------------------------------
Performance_Rating
[]
--------------------------------------------------
Training_Hours_Last_Year
[]
--------------------------------------------------
Project_Count
[]
--------------------------------------------------
Average_Hours_Worked_Per_Week
[]
--------------------------------------------------
Absenteeism
[]
--------------------------------------------------
Work_Environment_Satisfaction
[]
--------------------------------------------------
Relationship_with_Manager
[]
--------------------------------------------------
Job_Involvement
[]
--------------------------------------------------
Distance_From_Home
[]
--------------------------------------------------
Number_of_Companies_Worked
[]
--------------------------------------------------

### target analysis

- What is the distribution of employee attrition?

In [10]:
fig = px.histogram(df,x="Attrition",histnorm="percent",text_auto=".1f",title="Employee Attrition Distribution (%)")

fig.update_traces(texttemplate="%{y:.1f}%")
fig

- Approximately 80% of employees stayed with the company, while around 20% left. This indicates that employee attrition exists but affects a minority of the workforce.

### Univariate Analysis

In [11]:
df.select_dtypes(include='number').columns

Index(['Employee_ID', 'Age', 'Job_Level', 'Monthly_Income', 'Hourly_Rate',
       'Years_at_Company', 'Years_in_Current_Role',
       'Years_Since_Last_Promotion', 'Work_Life_Balance', 'Job_Satisfaction',
       'Performance_Rating', 'Training_Hours_Last_Year', 'Project_Count',
       'Average_Hours_Worked_Per_Week', 'Absenteeism',
       'Work_Environment_Satisfaction', 'Relationship_with_Manager',
       'Job_Involvement', 'Distance_From_Home', 'Number_of_Companies_Worked'],
      dtype='object')

- Numerical Features

In [12]:
for col in df.select_dtypes(include='number').columns.drop('Employee_ID'):
    fig = px.box(
        df,
        y=col,
        title=f"{col} Distribution"
    )
    fig.show()

- Categorical Features

In [13]:
for col in df.select_dtypes(include="object").columns:
    fig = px.histogram(
        df,
        x=col,
        text_auto=True,
        title=f"{col} Distribution",
        category_orders={
            col: df[col].value_counts().index.tolist()
        }
    )

    fig.show()

### Bivariate Anakysis

- Attrition Vs Department

In [15]:
dep = df.groupby("Department")["Attrition"].value_counts(normalize=True).reset_index(name="Percentage")

fig = px.bar(dep, x="Department", y="Percentage", color="Attrition", text_auto=".1%")
fig.show()

- Attrition rates are very similar across all departments, suggesting that department is not a strong factor associated with employee attrition.

### Attrition Vs Overtime

In [16]:
ot = df.groupby("Overtime")["Attrition"].value_counts(normalize=True).reset_index(name="Percentage")

fig = px.bar(
    ot,
    x="Overtime",
    y="Percentage",
    color="Attrition",
    text_auto=".1%"
)

fig.show()

- Overtime shows a noticeable association with attrition, with employees working overtime having a higher proportion of attrition.

### Attrition Vs Monthly income

In [17]:
fig = px.box(
    df,
    x="Attrition",
    y="Monthly_Income",
    title="Monthly Income vs Attrition"
)

fig.show()

### Attrition Vs Job Satisfaction

In [18]:
fig = px.box(
    df,
    x="Attrition",
    y="Job_Satisfaction",
    title="Job Satisfaction vs Attrition"
)

fig.show()

- Job Satisfaction has an almost identical distribution for employees who stayed and those who left, suggesting that it is not a strong factor associated with attrition.

### Job_Involvement vs Attrition

In [19]:
chart = px.box(
    df,
    x="Attrition",
    y="Job_Involvement",
    title="Job Involvement vs Attrition"
)

chart.show()

- Employees who left show a slightly wider and higher distribution of Job Involvement, although the median is the same for both groups.

### Work_Life_Balance vs Attrition

In [20]:
chart = px.box(
    df,
    x="Attrition",
    y="Work_Life_Balance",
    title="Work-Life Balance vs Attrition"
)

chart.show()

- Employees with attrition have a higher median Work-Life Balance score (3) compared with employees who stayed (2).

### years at company vs attrition

In [21]:
chart = px.box(
    df,
    x="Attrition",
    y="Years_at_Company",
    title="Years at Company vs Attrition"
)

chart.show()

- Years at Company does not show a clear difference between employees who stayed and those who left.

### Distance_From_Home vs Attrition

In [22]:
chart = px.box(
    df,
    x="Attrition",
    y="Distance_From_Home",
    title="Distance From Home vs Attrition"
)

chart.show()

- Distance From Home shows a very similar distribution between employees who stayed and those who left, with only a slight difference in the median.

### Job Role vs Attrition

In [23]:
order = df[df["Attrition"] == "Yes"]["Job_Role"].value_counts().index.tolist() # for ordering the job roles based on the number of attrition cases

fig = px.histogram(
    df,
    x="Job_Role",
    color="Attrition",
    text_auto=True,
    category_orders={"Job_Role": order}
)

fig.show()

- Attrition rates are relatively similar across job roles, with Assistant having the highest attrition rate and Manager the lowest. However, the differences are not very large.

- Age vs Attrition

In [24]:
chart = px.box(
    df,
    x="Attrition",
    y="Age",
    title="Age vs Attrition"
)

chart.show()

- Age shows a very similar distribution between employees who stayed and those who left, suggesting that age is not a strong factor associated with attrition in this dataset.

### Performance Rating vs Attrition

In [25]:
chart = px.box(
    df,
    x="Attrition",
    y="Performance_Rating",
    title="Performance Rating vs Attrition"
)

chart.show()

- Employees who left the company tend to have higher performance ratings than those who stayed, suggesting a potential retention issue among higher-performing employees

### ML